### ISSUE TITLE
An suggestion for having all your themes in one place

### ISSUE THREAD

**Issue by austinrojers** [JezerM/web-greeter#24]
## Description of feature

Hey there @JezerM, I wondered if you could add _glorious_, _aether_, and _litarvan_ themes here: https://github.com/JezerM/web-greeter/tree/master/themes, instead of someone would have to clone your fork and copy it to /usr/share/web-greeter/themes/?

In the case of _litarvan_ you also have to build it first.

**Comment by JezerM** [comment]
Hi~ I think that's not possible.

**web-greeter** should only contain its own themes. Third party themes are needed to be manually installed because of these reasons:

- Some of them needs a build process, so it would mean to include a built theme or build them on web-greeter's build process; it's a lot to maintain.
- They have different Licenses, therefore they can affect the current web-greeter license.
- Because of their Licenses (and even without them), I think it's unethical to include 3rd party themes without their consent.
- Also, the recognition of these themes could be lowered if installed from other ways (web-greeter).
- Even if some of them are my forks, they aren't mines.

Unless the themes are completely abandoned and I decided to work on them with lots of changes and improvements, they won't be included as part of web-greeter.

The most I could do it's to reference them inside the README.

**Comment by austinrojers** [comment]
oh, I didn't know that, sorry for my ignorance

**Comment by austinrojers** [comment]
I think

**Comment by JezerM** [comment]
No problem~

**Comment by austinrojers** [comment]
One thing you could do is you could edit the _readme_ file of your theme forks according to your installation instructions.
The instructions there are for the original project and could be little confusing.
