### ISSUE TITLE
Login screen in main monitor

### ISSUE THREAD

**Issue by sergius02** [JezerM/web-greeter#26]
Hi 👋!

I have installed the last version 3.2.1 in Regolith (Ubuntu 21.10 with i3wm), but the login box keeps displaying in my second monitor.

I have this in /etc/lightdm/lightdm.conf:
display-setup-script=xrandr --output DisplayPort-3 --primary

This should set my main monitor as primary, but it doesn't work.

**Comment by JezerM** [comment]
I do not have a second monitor, so I can't reproduce your problem. However, according to LightDM documentation, `display_setup_script` requires a path to the actual script, not the sh script itself. So, instead of `xrandr --output [Monitor] --primary`, use `/path/to/your/script` (not in /home).

I did a

**Comment by JezerM** [comment]
I do not have a second monitor, so I can't reproduce your problem. However, according to LightDM documentation, `display_setup_script` requires a path to the actual script, not the sh script itself. So, instead of `xrandr --output [Monitor] --primary`, use `/path/to/your/script` (not in /home).

I did a little research and found this gist comment: https://gist.github.com/RyanMillerC/c48d9f63f8fe386b22a7da18cf6913d2#gistcomment-2332917. Also, check out this other comment: https://gist.github.com/RyanMillerC/c48d9f63f8fe386b22a7da18cf6913d2#gistcomment-2762963

**Comment by sergius02** [comment]
Acording to this https://askubuntu.com/a/1228402 you can write a command too in that property.

I tried to make the script, making it executable but the result is the same

**Comment by JezerM** [comment]
According to this other comment: https://askubuntu.com/a/470858, you could try to set both `display-setup-script` and `session-setup-script` with the same script. But, at the end, this is more a LightDM "issue" than web-greeter "issue".
