### ISSUE TITLE
Login dialog supports more screens.

### ISSUE THREAD

**Issue by raven2cz** [JezerM/web-greeter#57]
I have laptop and connected external LCD. The web-greeter is shown on laptop screen only. The screen is not mirroring with web-greeter, but extended. In main external LCD is shown just wallpaper only without possibility to sign in. 

Is it possible to show login dialog in all screens or moved the login dialog to active screen where mouse is?

**Comment by JezerM** [comment]
Hi, sorry for the late response, I was busy~

> The screen is not mirroring with web-greeter, but extended.

It is this way merely by design; the main screen has the login prompt, while the other screens only show the wallpaper. Having a duplicate of the main screen on all screens wouldn't look very well. Still, this is a Theme decision.

> Is it possible to show login dialog in all screens or moved the login dialog to active screen where mouse is?

About the second, I think it could be done, but I don't have an external monitor to test it and it's not in my plans. However, you could do the first one.

You can show the login dialog in all screens by editing the `index.yml` file that comes with some themes. Inside this file, you can specify which HTML file web-greeter should use for the main screen, and which one to use in other screens. So, you could set the `secondary_html` as `"index.html"` (the same as `primary_html`), and in this way web-greeter will use the same HTML for all screens.

By default, the same HTMl is used in all screens unless specified in `index.yml`, which is a design decision for each theme.

**Comment by raven2cz** [comment]
@JezerM Nice solution, it works, thank you!
